version: 5.1.{build}.{branch}
environment:
  access_token:
    secure: vsDaeFdGCIGlIxWSEdsDomYtr5mKS5IPGHc4NwuDZ5D6mCna0STrDvMZ6IP6mOBK
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
os: Visual Studio 2015
configuration: Release
shallow_clone: false
clone_depth: 1
clone_folder: C:\Repos\StepMania
init:
- cmd: >-
    git config --global credential.helper store

    set GITHUB_API_URL=https://api.github.com/repos/%APPVEYOR_REPO_NAME%/statuses/%APPVEYOR_REPO_COMMIT%

    set APPVEYOR_BUILD_URL=https://ci.appveyor.com/project/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%/build/%APPVEYOR_BUILD_VERSION%

    set SM_COMMIT_SHORT=%APPVEYOR_REPO_COMMIT:~0,7%

    set SM_SETUP_EXE_NAME=StepMania-5.1-git-%SM_COMMIT_SHORT%-win32.exe

install:
- cmd: >-
    choco install cmake

    choco install nsis -version 2.46.0.20150406
before_build:
- cmd: >-
    choco upgrade cmake

    set path=C:\Program Files\CMake\bin;%path%

    cd Build

    cmake -G "Visual Studio 14 2015" -T "v140_xp" -DWITH_IRC_POST_HOOK=ON ..
build_script:
  - cmake --build . --config %CONFIGURATION% --parallel 2
artifacts:
  - path: Build/*.exe
    type: exe
on_success:
- cmd: >-
    echo "Posting to IRC now..."

    rem C:\Repos\StepMania\Program\irc-reporter.exe "%APPVEYOR_REPO_NAME%" "%APPVEYOR_BUILD_VERSION%"  "%SM_COMMIT_SHORT%" "%APPVEYOR_REPO_COMMIT_AUTHOR%" "%APPVEYOR_BUILD_URL%" "success"
on_failure:
- cmd: >-
    echo "Posting to IRC now..."

    rem C:\Repos\StepMania\Program\irc-reporter.exe "%APPVEYOR_REPO_NAME%" "%APPVEYOR_BUILD_VERSION%" "%SM_COMMIT_SHORT%" "%APPVEYOR_REPO_COMMIT_AUTHOR%" "%APPVEYOR_BUILD_URL%" "failure"
