language:
  - cpp
  - c
notifications:
  email: false
  irc: "chat.freenode.net#stepmania"

os:
  - linux
  - osx

env:
  - BUILD_TYPE=Release

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libasound2-dev
      - libglew-dev
      - libmad0-dev
      - libpulse-dev
      - libva-dev
      - libvorbis-dev
      - libxinerama-dev
      - libxrandr-dev
      - yasm

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew upgrade cmake; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install yasm; fi

before_script:
  - cd Build
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CMAKE_MAKE_PROGRAM="Unix Makefiles"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CMAKE_MAKE_PROGRAM=Xcode; fi
  - cmake .. -G"${CMAKE_MAKE_PROGRAM}"
    -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
    -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX}
    -DWITH_FFMPEG_JOBS=2

script:
  - cmake --build . --parallel 2
